name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: localhost

    steps:
    - uses: actions/checkout@v3
    - name: Docker version
      run: docker --version
    - name: Docker Container List
      run: docker ps
